apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ncaiweb
  namespace: websites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ncaiweb
  template:
    metadata:
      labels:
        app: ncaiweb
    spec:
      containers:
      - name: app
        image: ENV_DOCKER_IMAGE
        env:
            - name: APIPATH
              value: https://api.ncai.cl/
---
apiVersion: v1
kind: Service
metadata:
  name: ncaiweb
  namespace: websites
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: ncaiweb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ncaiweb
  namespace: websites
spec:
  rules:
  # Change this to your own hostname
  - host: web.ncai.cl
    http:
      paths:
      - path: /
        pathType : ImplementationSpecific
        backend: 
          service:
              name: ncaiweb
              port:
                number: 80