apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pixel-world
  namespace: websites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixel-world
  template:
    metadata:
      labels:
        app: pixel-world
    spec:
      containers:
      - name: app
        image: lnavarrocarter/pixel-world:latest
---
apiVersion: v1
kind: Service
metadata:
  name: pixel-world
  namespace: websites
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: pixel-world
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixel-world
  namespace: websites
spec:
  rules:
  # Change this to your own hostname
  - host: pixel-game.lnavarro.dev
    http:
      paths:
      - path: /
        pathType : ImplementationSpecific
        backend:
          service:
              name: pixel-world
              port:
                number: 80
