apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ncaiweb
spec:
  rules:
  # Change this to your own hostname
  - host: web.ncai.cl
    http:
      paths:
      - path: /
        pathType : ImplementationSpecific
        backend: 
          service:
              name: ncaiweb
              port:
                number: 80