name: Deploy Ncai Kubernetes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image push DOCKER HUB
      env:
        REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
        USER: ${{secrets.DOCKER_USER}}
        TOKEN : ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $USER --password $TOKEN
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "ENV_DOCKER_IMAGE"
        replace: "${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}"
        include: ".kube/**"
        regex: false
      

    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '["**/*.yml"]'   
      env:
       API_HOST: ${{secrets.API_HOST}}


    - name: Trigger deploy
      uses: phamquyhai/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f .kube/deploy.yml
