name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image push DOCKER HUB
      env:
        REGISTRY: ${{ secret.DOCKER_HUB.DOCKER_REGISTRY }}
        REPOSITORY: ${{ secret.DOCKER_HUB.DOCKER_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
        USER: ${{secret.DOCKER_HUB.DOCKER_USER}}
        TOKEN : ${{secret.DOCKER_HUB.DOCKER_TOKEN}}
      run: |
        docker login $USER --password $TOKEN
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
